

const Screens = {
	LOGIN_SCREEN:"LOGIN_SCREEN",
	SIGN_UP_SCREEN:"SIGN_UP_SCREEN",
	SPLASH_SCREEN:"SPLASH_SCREEN",
	WELCOME_SCREEN:"WELCOME_SCREEN",
	HOME_SCREEN:"HOME_SCREEN",
	ADD_SCREEN:"ADD_SCREEN",
	PROFILE_SCREEN:"PROFILE_SCREEN",
	HOME_STACK:"HOME_STACK",
	PRESCRIPTIONS_SCREEN:"PRESCRIPTIONS_SCREEN",
	ACCOUNT_SCREEN:"ACCOUNT_SCREEN",
	ALL_PHARMACIES_SCREEN:"ALL_PHARMACIES_SCREEN"
}
export default Screens
