

const Screens = {
	LOGIN_SCREEN:"LOGIN_SCREEN",
	SIGN_UP_SCREEN:"SIGN_UP_SCREEN",
	SPLASH_SCREEN:"SPLASH_SCREEN",
	WELCOME_SCREEN:"WELCOME_SCREEN",
	HOME_SCREEN:"HOME_SCREEN"
}
export default Screens
